### ISSUE TITLE
Name copy-to-clipboard as dependency

### ISSUE THREAD

**Issue by jthn** [pocka/figspec#19]
Thanks for this package.

It appears that [here](https://github.com/pocka/figspec/blob/0b8cf9f2c993017ea6dbad70226f57dc9d88ce71/packages/components/src/FigspecViewer/InspectorView/InspectorView.ts#L2) you're using `copy-to-clipboard`, but it isn't declared as a dependency.

Yarn is complaining about it. I have an override in place on my local system, but you most likely want to add that as a peer dependency, as I believe it gets added by storybook.

**Comment by pocka** [comment]
Fixed in [`@figspec/components`@v0.1.6](https://github.com/pocka/figspec/releases/tag/components%2Fv0.1.6)
