### ISSUE TITLE
Script generates only an empty file

### ISSUE THREAD

**Issue by Tim-arts** [pocka/figspec#27]
Hello, I've tried to set up the figspec plugin into my project and everytime I'm running the command to generate the files I get this error:

> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from C:\Users\path\to\scripts\generateStaticFigmaFile\index.mjs
>     at packageResolve (internal/modules/esm/resolve.js:650:9)
>     at moduleResolve (internal/modules/esm/resolve.js:691:18)
>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:784:11)
>     at Loader.resolve (internal/modules/esm/loader.js:100:40)
>     at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
>     at link (internal/modules/esm/module_job.js:46:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> error Command failed with exit code 1.

I've tried to replace:
`import * as fs from "fs/promises";`
By:
`import { promises as fs } from 'fs';`

But when I execute the command, the folder contains only an empty file. Any idea how to fix this?

**Comment by Tim-arts** [comment]
Updating Node has fixed the error but the generation succeeds with only one empty file created:

![image](https://user-images.githubusercontent.com/10064887/127567512-698f1147-a529-4484-a3ec-10184d91f4a8.png)

**Comment by Tim-arts** [comment]
@pocka I've found the issue, it seems that the filesystem on my side is struggling to create file containing ":" in their names. I've tried this and the files are actually being created: 

// Current implementation
`await Promise.all(
    files.map(async (file) => {
      await fs.writeFile(path.resolve(outDir, file.filename), file.data);
    })
  );`
  
// What works on my side
`await Promise.all(
    files.map(async (file) => {
      await fs.writeFile(path.resolve(outDir, file.filename.replace(':', '-')), file.data);
    })
  );`

**Comment by pocka** [comment]
AFAIK, the script is tested/run only on Linux (maybe macOS too?). Since the script is for development and testing, feel free to create a PR for the files.
