### ISSUE TITLE
When displaying complex frames the figspec viewer selection becomes really slow and displays visual artifacts

### ISSUE THREAD

**Issue by Tim-arts** [pocka/figspec#30]
### Affected design types

- [ ] figma
- [X] figspec
- [ ] link
- [ ] image
- [ ] iframe

### Describe the bug

The Figspec viewer selection utility is very slow while displaying a complexe frame, as much that it becomes impossible to maneuver in the frame. There's a video describing the issue: [https://youtu.be/OZe-T3u_acE](https://youtu.be/OZe-T3u_acE)

On Firefox it's not as worse as shown on Chrome, you can feel the lag but there won't be any artifact

### How to reproduce the bug?

Create a complex frame in Figma and load it into Storybook through the Figspec viewer (the component/symbol shown in the video has 580 variants)

### Expected behaviour

The viewer display the information as it should without latency and visual artifacts.

### Environment

- [X] Chrome / Chromium / Chromium based browsers
- [X] Firefox
- [ ] macOS Safari
- [ ] iOS Safari
- [ ] Samsung Internet
- [ ] Other

### Affected versions

6.2.1

### Storybook versions

6.4.9

**Comment by Hideman85** [comment]
I have a similar issue even with relatively small number of nodes.
The issue I have is it is super laggy when inspector is open as shown below
![output](https://user-images.githubusercontent.com/16165119/169794773-d356b372-4152-49fe-8644-3d2e22e71344.gif)

**Comment by Tim-arts** [comment]
Hello @pocka , I've invited you to join a Figma file where you can have full access

**Comment by pocka** [comment]
I'll take a look at the file and see if a fix for #37 improves performance issues.

**Comment by pocka** [comment]
It seems there are many factors causing this poor performance:

- Lit's `render` function iterates every nodes twice per property change (including internal ones, such as scaling factor)
- SVG images -- SVG rendering + CSS transform is not performant enough for this usage
- Guideline strokes needs to be updated on every scale changes

I tested on a WIP plain DOM implementation (removed Lit to minimize update) with the largest frame from [Twemoji](https://www.figma.com/community/file/806291777034672116/%F0%9F%98%8E---Twemoji-by-Twitter) file (frame JSON ... 13MB, frame SVG ... 7MB). The newer implementation is slightly more performant than the current implementation, but still unusably laggy/sluggish.

Probably WebGL is the only[^0] choice... though it takes a lot of effort to implement.

[^0]: WebGPU and fallback WebGL renderer using `wgpu` would be more performant, but using WASM makes package structure/publishing/usage too complicated. If this was a standard application, Worker + WASM is definitely the way to go.

**Comment by pocka** [comment]
Fixed in v2.0.0 ([release note](https://github.com/pocka/figspec/releases/tag/v2.0.0), [npm](https://www.npmjs.com/package/@figspec/components/v/2.0.0))
