### ISSUE TITLE
Inspector

### ISSUE THREAD

**Issue by pocka** [pocka/figspec#4]
Show props such as font family, size, color.

**Comment by yannbf** [comment]
Let me give this a try, we can work together to make it work nicely!

**Comment by pocka** [comment]
Sorry for the too short description :alien:

My initial idea is a separate inspector panel like Figma's right sidebar.

```js
const [selectedNode, setSelectedNode] = useState(null)

// usage in React
const onSelectNode = ev => {
  setSelectedNode(ev.detail.node)
}

// node selection event is not implemented though
return <figspec-viewer onSelectNode={onSelectNode}>
  <figspec-inspector node={selectedNode} />
</figspec-viewer?
```

Pros:
- Can keep the viewer component simple
- Opt-in = lightweight, free to choose

Cons:
- Loose integration than an all-in-one component

WDYT?

**Comment by yannbf** [comment]
No problem at all haha
Sounds like an interesting idea, although me as a user would prefer to have this out of the box for the best experience. Any way you prefer is great though! If the inspector grows to something a bit more complex that could involve code highlight etc that would require more libs, maybe it's a good idea to have it separate indeed.

**Comment by pocka** [comment]
> although me as a user would prefer to have this out of the box for the best experience.

Indeed the out of the box usage is better than modularity for this niche library! Thank you for reminding me “Premature optimization is the root of all evil” 👍

**Comment by pocka** [comment]
#12

**Comment by pocka** [comment]
v0.1.4
